// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("miniscaffold-2022-stir-trek")>]
[<assembly: AssemblyProductAttribute("miniscaffold-2022-stir-trek")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-04-04T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","17b3de0f947364d25b8ae207857a3149dd4f2134")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "miniscaffold-2022-stir-trek"
    let [<Literal>] AssemblyProduct = "miniscaffold-2022-stir-trek"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-04-04T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "17b3de0f947364d25b8ae207857a3149dd4f2134"
